### ISSUE TITLE
.env STRIPE_PUBLISHABLE_KEY not found

### ISSUE THREAD

**Issue by alexookah** [scottyzen/woonuxt#102]
I have created a .env and added the `STRIPE_PUBLISHABLE_KEY` but it keeps telling me in the checkout page key not found!
What could be the issue?

**Comment by magecommerce** [comment]
same issue

**Comment by alexookah** [comment]
Created a [PR](https://github.com/scottyzen/woonuxt/pull/103) that fixes this issue

**Comment by alexookah** [comment]
@magecommerce Can you try the latest nuxt version from master branch? I cant seem to reproduce this issue anymore
