### ISSUE TITLE
Override AppHeader

### ISSUE THREAD

**Issue by alexookah** [scottyzen/woonuxt#104]
I can't seem to manage to override the `AppHeader.vue`.
i have tried creating a folder in the root `components/generalElements/AppHeader.vue`
but it's not reading the override.
Is there something missing for this?

(I managed to override `CategoryCard.vue` which is inside components folder but not the ones that are inside `generalElements`.

**Comment by alexookah** [comment]
Made a [PR](https://github.com/scottyzen/woonuxt/pull/106) that fixes this
@scottyzen  have a look.

**Comment by scottyzen** [comment]
Thanks again for this @alexookah. Great spot 👍🏻
