### ISSUE TITLE
Error fetching woonuxt-settings + Proxy error

### ISSUE THREAD

**Issue by GuillaumeDgr** [scottyzen/woonuxt#117]
Hi, 

I have started a fresh new woonuxt install with my existing wordpress backend but I have below errors when running npm install or yarn install:
<img width="490" alt="Screenshot 2024-01-22 at 16 40 23" src="https://github.com/scottyzen/woonuxt/assets/29545767/80cb4acd-53da-456a-acd0-c5f4339d0f3e">

I have downloaded and installed latest woonuxt-settings plugin version (1.0.51):
![Screenshot 2024-01-22 at 16 40 08](https://github.com/scottyzen/woonuxt/assets/29545767/f93a55c8-bf8b-4f71-ab7f-511649bbe6bd)
<img width="248" alt="Screenshot 2024-01-22 at 16 49 44" src="https://github.com/scottyzen/woonuxt/assets/29545767/c2bf7eed-e772-4777-b6f3-bcecdebb5467">

When i run npm run dev or yarn dev, I'm facing below error (graphql returns data, but then cast seems to bug):
![Screenshot 2024-01-19 at 17 52 54](https://github.com/scottyzen/woonuxt/assets/29545767/b6779adb-d8ba-4072-b4d3-5a5202f8dd10)
![Screenshot 2024-01-19 at 17 53 19](https://github.com/scottyzen/woonuxt/assets/29545767/22dd6f30-0945-499f-8f76-f0d68d27bc64)

Any help on this pls?

Many thanks!!

**Comment by alexookah** [comment]
Hi
@GuillaumeDgr 
i already made a similar issue in the repo of woonuxt-settings:
https://github.com/scottyzen/woonuxt-settings/issues/6

Made a PR that fixes this issue. My PR fix was not added in a new woonuxt-version package.
Just download master folder zip it and upload it as a plugin update.
should work.

**Comment by GuillaumeDgr** [comment]
Wow!! You can't imagine how grateful I am! 
I've been trying to figure out why it does not work for two days! I don't know how I missed your post on the woonuxt-settings github, I thought I looked! 

Thank you very much, everything is resolved!

**Comment by alexookah** [comment]
feel free to close this issue since it's resolved
