### ISSUE TITLE
Question: How to use & add images in overriden components

### ISSUE THREAD

**Issue by alexookah** [scottyzen/woonuxt#118]
Hello @scottyzen,

I'm working on customising the `Logo.vue`. To achieve this, I plan to create a new Logo.vue file in the following directory: `components/generalElements/`. This new component will reference a different image using `NuxtImg`.

I have a question regarding the storage of this new image. Should the image be placed in the `woonuxt_base/static/images` directory? This query arises because our `nuxt.config.ts` file, located at `woonuxt_base/nuxt.config.ts`, seems to configure image directories as follows:

```
image: {
  domains: process.env.NUXT_IMAGE_DOMAINS ? process.env.NUXT_IMAGE_DOMAINS.replace(/ /g, '').split(',') : [],
  dir: resolve('./static'),
},
```

Given this configuration, would it be more appropriate to store the new image for `Logo.vue` in a different directory, or is placing it in the `woonuxt_base/static/images` directory suitable? 
I tried to use ../../../Image shows, but the `webp` images don't get optimized for `webp`.

Looking forward to your guidance on this matter.
Thank you!

**Comment by scottyzen** [comment]
Hi @alexookah, There was an issue with NuxtImg but they fixed it recently. I've updated WooNuxt to fix it now too. Here is the example of how to customize the ```Logo.vue``` component and use NuxtImg. https://github.com/scottyzen/woonuxt/tree/example/custom-logo
