### ISSUE TITLE
Missing "n" to span tag

### ISSUE THREAD

**Issue by GuillaumeDgr** [scottyzen/woonuxt#119]
In OrderSummary line 18
![Screenshot 2024-01-24 at 15 35 34](https://github.com/scottyzen/woonuxt/assets/29545767/18c735cc-2f75-42ac-aa98-853f9280a645)

**Comment by scottyzen** [comment]
Thanks, @GuillaumeDgr, I only spotted it myself the other night. It's coming in the upcoming [PR](https://github.com/scottyzen/woonuxt/pull/116/files#diff-03bd3ec91b0dd4d564131b90ee8dc365e910c84c0998b70fa4c4e31fdbc4828d)
