### ISSUE TITLE
nuxt-preview ... Cannot query field "allPaColor" ...

### ISSUE THREAD

**Issue by pburel** [scottyzen/woonuxt#13]
Hello,

I got error 

1)  FATAL  Failed to run command nuxt-preview:                                                                                                             11:29:05
Error: Command failed with ENOENT: nuxt-preview
spawn nuxt-preview ENOENT

2) Error: Cannot query field "allPaColor" on type "VariableProduct".: {"response":{"errors":[{"message":"Cannot query field \"allPaColor 

idem for allPasize, image gallery / sourceUrl ...
Which plugin do you use for variation ?

Any idea to resolve ?

Your solutions seems great !
Pascal
keep up the good work !

**Comment by scottyzen** [comment]
Hi @pburel. I need to fix this to make it not required. In the meantime, a quick fix it to just add color as a global attribute in your WooCommece store.
