### ISSUE TITLE
Cart Updating Quantity

### ISSUE THREAD

**Issue by Quinesee** [scottyzen/woonuxt#133]
Hi,
I noticed this issue on the staging site: https://v3.woonuxt.com/product/flying-ninja and locally. 
It happens when you add a product to your cart and then increase the quantity in the cart using a mouse, by clicking the little number arrow. The update quantity gets stuck in a loop and the quantity continues to grow indefinitely. You also can't interact with page because it is stuck in cart update.

What is interesting is that if you type a number in, this doesn't happen.

Testing this on different browsers, I get the same results. In edge and chromium, the quantity number doesn't continue to increment but you do get stuck in an infinite loop. In firefox, you can see the quantity increasing.

**Comment by Kythonlk** [comment]
This happen in cart and checkout also 
![image](https://github.com/scottyzen/woonuxt/assets/109597262/28f7d7b8-bc29-41eb-a844-d3fe2f57e5e7)

**Comment by scottyzen** [comment]
I've just updated the cart. It's working for me on the demo. If ye are still having issues please let me know. And if there is anything showing in the console. Thanks

**Comment by Kythonlk** [comment]
Still have the issue i think state contentiously updating by loop and now  count is not showing

![image](https://github.com/scottyzen/woonuxt/assets/109597262/3ee8373b-e055-45b8-afe3-a8818cf044ef)

**Comment by scottyzen** [comment]
Thanks @Kythonlk. I've just added a debounce to the input. I think that was the cause! Thanks for the heads up 👍🏻
