### ISSUE TITLE
Nuxt 3

### ISSUE THREAD

**Issue by w3bdesign** [scottyzen/woonuxt#15]
Any plans for converting this project to Nuxt 3?

I have recently converted https://github.com/w3bdesign/nuxtjs-woocommerce to Nuxt 3 and may help out a little if necessary.

**Comment by w3bdesign** [comment]
@scottyzen

**Comment by scottyzen** [comment]
Hi @w3bdesign. Yea, I actually have it converted to Nuxt 3 already. I'll be swapping it over on this repo sometime during the week. Thanks anyway, I appreciate it 👍🏻
