### ISSUE TITLE
Probably SSL isue? Error when logging in form woonuxt front-end

### ISSUE THREAD

**Issue by maxose01** [scottyzen/woonuxt#159]
When I try to log in my account in woonuxt I get the following error (with correct data)

"Password was correct, but there was an error logging in. Please try again later. If the problem persists, please contact support."

Does anyone have an idea how I can fix this? When I look in the code snippet, cart is apparently not null and viewer is. What does viewer do?

if (loginWithCookies?.status === 'SUCCESS') { const cart = await refreshCart(); console.log(cart); console.log(viewer); if (cart && viewer.value === null) { return { success: false, error: 'Password was correct, but there was an error logging in. Please try again later. If the problem persists, please contact support.' }; } } else {

**Comment by scottyzen** [comment]
Hey @maxose01, it could be a CORS issue. Can you send me your GrapghQL endpoint and I'll have a look for you?

**Comment by maxose01** [comment]
Hey, It was solved by moving to another provider and server for Wordpress. Thankyou!
