### ISSUE TITLE
woo.nuxt.dev

### ISSUE THREAD

**Issue by zackha** [scottyzen/woonuxt#213]
Hi @scottyzen,

Long time no see!

If you're thinking of deploying Woonuxt on Nuxt's hub, I've got your domain ready: [woo.nuxt.dev](https://woo.nuxt.dev/). Just giving you a heads-up.

Let me know when you switch to the hub, and I'll hand it over to you during deployment.

Cheers,

**Comment by scottyzen** [comment]
Hi @zackha ,

Thanks for that and sorry for getting back to you so late. I was offline for a couple of weeks. Just catching up on everything now. What do I need to get it set up? I've read about Nuxt's hub but haven't had the time to dive into it properly.

Thanks for the heads up.

**Comment by zackha** [comment]
Hi @scottyzen,

No worries, I hope you had a great vacation!

You can create an account and import your project at https://admin.hub.nuxt.com, just like you would with Netlify or Vercel. It's all powered by Cloudflare in the background.

During the setup, simply type "**woo**" in the name field, and a link for deployment will be generated below.

Just let me know right before you do this, so I can activate the link for you.

![Screenshot 2024-08-25 at 03 44 31](https://github.com/user-attachments/assets/3fe7eb2e-330c-4bf4-804e-f5114d309875)

![Screenshot 2024-08-25 at 03 45 37](https://github.com/user-attachments/assets/fca932e2-b47a-4e92-8dcc-bfeea977912c)

**Comment by scottyzen** [comment]
Hey @zackha, I have that set up now. https://woo-scottyzen.nuxt.dev/

**Comment by zackha** [comment]
Hey @scottyzen ,

Now you can use the "woo" domain name. Just simply type "woo" in the name field.

**Comment by scottyzen** [comment]
Awesome, Thanks @zackha 👏🏻

https://woo.nuxt.dev

**Comment by zackha** [comment]
You're welcome! Wishing you continued success! 😊

**Comment by scottyzen** [comment]
You too @zackha, much appreciated 🙂
