### ISSUE TITLE
Password reset link is invalid

### ISSUE THREAD

**Issue by grandant** [scottyzen/woonuxt#244]
Hi, thanks for the great work.

I am testing with:

- WooCommerce 9.2.3
- WooNuxt Settings 1.0.58
- WPGraphQL WooCommerce (WooGraphQL) 0.21.0

Whenever I try to test the password reset functionality I get:

`Password reset link is invalid.[Please request a new link](https://rondo-frontend-test.nuxt.dev/my-account?action=forgotPassword)`

![image](https://github.com/user-attachments/assets/94c9fd06-d9da-4e51-a71d-9706dbda8ac4)

There aren't any errors in the dev console or anywhere else that I can see.

**Comment by alexookah** [comment]
Interesting! @grandant 

I did some work to make this work actually in woocommerce codebase ([PR](https://github.com/woocommerce/woocommerce/pull/49737)).

Today September 10 is the release of 9.3 which should contain my change. Change is that the reset link contains the username (called "`login`") which is required for the reset password to happen.

Please try again with the 9.3 release of woocommerce once release and let me know if it worked!

**Comment by grandant** [comment]
Glad to hear that! I don't have any experience with WordPress but after a lot of trials I realized that the issue was exactly that. So I edited reset password template and I had to hard-code the production URL. So everything is working now. I realize this is less than ideal so I am looking forward to test your update.

1. Yes - I directly changed the template if that's your question
2. I hardcoded the Site Address into the template

I made some other changes as well to ensure that the WP Address and Site Address work separately.

There were several other issues as well. Maybe some of them are due to my very limited knowledge of WordPress configuration but if you are interested I can share my findings.

**Comment by alexookah** [comment]
Well if you have edited the template then you might need to re-edit it and include the login parameter. Unless it gets reset once you update woocommerce to 9.3.
In my setup I found that using the plugin` Simple Website Redirect` worked fine. Simply all wordpress front-end urls are redirecting to the headless website. So no need to edit any template.

https://wordpress.org/plugins/simple-website-redirect/

![Screenshot 2024-09-10 at 10 44 51](https://github.com/user-attachments/assets/9529cfb1-0792-4732-a127-99dc4e462728)

Exclude Query Parameters: `download_file,wc-api,graphql,wc-ajax`
Exclude Paths: `/graphql,/wp-json,/wc-auth`

**Comment by grandant** [comment]
Thanks, that works good. It's important to have the WordPress installed in the root directory to avoid additional configuration. I re-installed everything so it's a clean install now. Just waiting for the WooCommerce update to be released to see if the login credentials will be included in the password reset link.

**Comment by alexookah** [comment]
Woocommerce 9.3.1 got released today and seems the username is provided in the reset link. 
Check it out @grandant

**Comment by grandant** [comment]
Yep, the issue is resolved. Thanks for the help @alexookah
