### ISSUE TITLE
image broken on wishlist

### ISSUE THREAD

**Issue by M-GRV** [scottyzen/woonuxt#30]
Hey! Looks like on the demo and my deployed test that the wishlist page shows broken images.

Wanted to make you aware!

**Comment by scottyzen** [comment]
Hey @M-GRV, Thanks for the heads up. It should be back working now 👍🏻

**Comment by M-GRV** [comment]
beautiful! I am fully testing what you have built. Anything else I find I'll let you know, but so far this is a really great repo and so promising for this community. TY!

**Comment by scottyzen** [comment]
Great, Thanks again @M-GRV 👍🏻
