### ISSUE TITLE
Can't logged in with new user

### ISSUE THREAD

**Issue by Gypsy-147** [scottyzen/woonuxt#32]
hi,
i try to register that is ok but when im log in at login button loading and i saw on network have return success login but the page stuck on login page when im re-loading need to login again  

thank you in advance for your help

**Comment by Gypsy-147** [comment]
like this

![image](https://user-images.githubusercontent.com/60289811/234353376-4ca4986a-8a54-4b4e-aad1-cada2a691e3c.png)

**Comment by scottyzen** [comment]
Hey @Gypsy-147, I'm not sure what's happening. I might need a bit more info. Can you try clearing all your cache and cookies? Or maybe just try in an incognito window. Let me know how you get on 👍🏻

**Comment by Gypsy-147** [comment]
@scottyzen im try clearing all cache and cookies and try in incognito mode but still stug on login page you can try https://bestbudz-th.com/ im using cloudflair for make ssl and proxy for wordpress and one issue is when you place an order with non login when complete it show Something went wrong message different v2 when im try

![image](https://user-images.githubusercontent.com/60289811/234374123-7cf66b26-e933-40ed-8007-fe71664876f1.png)

**Comment by scottyzen** [comment]
Hey @Gypsy-147. I might have something to do with Cloudflare alright. In your WordPress dashboard, try to pay around with the `Samesite cookie mode` setting found under GrapghQL > Setting > CORS Settings. It might not solve it but it's worth a try. 

The error itself is separate from WooNuxt. You might find an answer here ([WP GraphQL CORS](https://github.com/funkhaus/wp-graphql-cors)) if the above doesn't work.

![Screenshot 2023-04-25 at 21 00 26](https://user-images.githubusercontent.com/5116925/234390262-e84b5666-7baa-456b-8cb7-9bc229c8f2ba.jpg)

**Comment by Gypsy-147** [comment]
@scottyzen wow im try to Strict mode can solve it tanks a lot brother
