### ISSUE TITLE
Account Login Issues

### ISSUE THREAD

**Issue by M-GRV** [scottyzen/woonuxt#33]
Looks like I can't login on the demo or on my own branch. I can register a user just fine. But it hangs on logging in.

**Comment by M-GRV** [comment]
> I think this is not implemented yet. See the [progress overview](https://github.com/scottyzen/woonuxt#progress) in the readme.

I see its still in active dev. Didn't know how far it was since the account pages do exist. Login auth does work, just doesnt redirect for me. But it was a different error on the public demo.

**Comment by scottyzen** [comment]
Hey @M-GRV, Login, and account page should be working. Are there any errors showing in your console or network tab?

**Comment by M-GRV** [comment]
@scottyzen its weird. I can now login into your demo just fine. But for myself it doesnt matter if the pass combo is right or wrong it just says logging you in than sits there. Just did a sync with the latest version of woonuxt as well. It is strange. 

No issues Im seeing in console or network tab. You can see the 200 responses for graphql when the button is clicked.

Registering a user works fine.

**Comment by scottyzen** [comment]
Hey @M-GRV. I just tried your store and I think the problem could be with the backend. I'm registered as a user on your site. If you want to make me an admin I'd be happy to take a look for you.

**Comment by M-GRV** [comment]
@scottyzen I will do that ty.

**Comment by M-GRV** [comment]
I dont see you as a user on my test store.  I think you might be looking at another one.
