### ISSUE TITLE
Cart functionality

### ISSUE THREAD

**Issue by PepeGonzale** [scottyzen/woonuxt#35]
I think it would be a good idea to put a button on each product in the cart to be able to delete it.

**Comment by scottyzen** [comment]
Hey @PepeGonzale. Your right. I have a 'swipe to remove item' component set up to remove the cart item for mobile. I'll add a button to that for desktop when I push it to prod.

**Comment by M-GRV** [comment]
> I think it would be a good idea to put a button on each product in the cart to be able to delete it.

In the meantime, you can currently move the quantity down to 0 and it will remove the single item from cart.

**Comment by scottyzen** [comment]
# Added now to master

- Cart delete item button (on Desktop) 
- Swipe to delete (on mobile)
