### ISSUE TITLE
Question about production

### ISSUE THREAD

**Issue by Gypsy-147** [scottyzen/woonuxt#36]
Hi 

I have question for deploy to production on netlify, When i'm add new product or review and approve it need to build to and deploy again with WooNuxt trigger right? Do you have any idea to resolve it if im add new products?

thank you in advance for your help

**Comment by scottyzen** [comment]
Hey @Gypsy-147. Yep! There's a really nice plugin for WordPress ([Deploy with NetlifyPress](https://wordpress.org/plugins/deploy-netlifypress/)) that you can easily configure to automatically trigger your Netlify build whenever you update or add a new product.

**Comment by Gypsy-147** [comment]
Thanks for the reply! i'll keep testing this for you
