### ISSUE TITLE
Do you have plan for showing content blog?

### ISSUE THREAD

**Issue by Gypsy-147** [scottyzen/woonuxt#37]
Hi

Do you have planing to show content blog from wordpress on front page?

**Comment by Zielgestalt** [comment]
Not sure this is useful, because the front page is something you want to customize anyways. But there’s a nice video with Daniel Roe showing how to use WordPress with Nuxt 3. So you can do it yourself. 
https://youtu.be/Whl-lfxH98U

**Comment by Gypsy-147** [comment]
@Zielgestalt Thanks a lot sir, that's very useful for me
