### ISSUE TITLE
integrate with storefront-ui

### ISSUE THREAD

**Issue by saifulazfar** [scottyzen/woonuxt#55]
i stumble upon with [storefront-ui](https://docs.storefrontui.io/v2/vue/getting-started.html) and i think its cool tailwind + nuxt3 ready commerce ui to be use with woonuxt...the only think storefront-ui missing are slider filter i guess compare to current woonuxt....can we plan to use the ui rather than reinvent the wheel (of ui)?

p/s : i like the way u use nuxt useState rather than use 3rd party state like pinia

**Comment by scottyzen** [comment]
Hey @saifulazfar. Thanks for the feedback. I don't think I'll go down the road of creating a slider or any type of component like that. Currently trying to ingratiate Nuxt's layer feature so the shop will easily be extended and customized. 

PS. useState is great. I'm trying to use as little 3rd party packages as possible. I could end up going with Pinia some day though 😅

**Comment by Atinux** [comment]
I love the idea of leveraging layers @scottyzen 🚀

**Comment by scottyzen** [comment]
> I love the idea of leveraging layers @scottyzen 🚀

Thanks, @Atinux ! And thanks for adding layers. It opens so many doors 👏🏻
