### ISSUE TITLE
Checkout shipping prices not updating when changing country

### ISSUE THREAD

**Issue by diegomassaroo** [scottyzen/woonuxt#63]
Good evening, my cart does not update shipping prices when the country is changed.

It only changes after I click the checkout button to proceed with the order. In fact, when I return to the checkout page the selected country finally appears and the shipping cost is updated correctly.

In Vue Devtools Browser Extension, under <CountrySelect>, it shows that the selector works fine and correctly captures the chosen country. I believe there might be some issues with updating the shipping cost when changing the country selector.

Any help is appreciated. Thank you so much!

**Comment by scottyzen** [comment]
Hi @diegomassaroo. I'm looking into it and will have an update shortly.

**Comment by scottyzen** [comment]
Hi @diegomassaroo. There's a fix just gone in for this: https://github.com/scottyzen/woonuxt/pull/65
