### ISSUE TITLE
CartCard and Checkout page only show maximum 10 products

### ISSUE THREAD

**Issue by GuillaumeDgr** [scottyzen/woonuxt#70]
CartCard only shows a maximum of 10 products. You cannot scroll vertically to see all the products.
![Screenshot 2023-10-02 at 15 56 48](https://github.com/scottyzen/woonuxt/assets/29545767/f72efff0-430e-4559-b3c2-f77d6d0454ce)

**Comment by scottyzen** [comment]
Hey @GuillaumeDgr . This is fixed now on the latest branch
