### ISSUE TITLE
New Deploy Broken

### ISSUE THREAD

**Issue by BlackDahlia313** [scottyzen/woonuxt#78]
Just tried a brand new wordpres install and brand new install of woonuxt and it isnt working anymore.

**Comment by esjau** [comment]
same

**Comment by BlackDahlia313** [comment]
```
Error: Cannot find module 'D:\nuxi\bin\nuxi.mjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by BlackDahlia313** [comment]
@scottyzen I am still having troubles deploying this on a fresh install. I can't install locally anymore and It fails building online. 

Everything else is set and I have had no issues before until these bigger changes.

**Comment by BlackDahlia313** [comment]
after updating everything latest on the new wordpress deployment:

![image](https://github.com/scottyzen/woonuxt/assets/44903742/a1402074-0e13-4065-8423-bf2df0f2122a)

**Comment by scottyzen** [comment]
Can you check if Enable Public Introspection is turned on? And WPGraphQL is
on version 1.17.0.

**Comment by scottyzen** [comment]
Also, can you send me your endpoint again? So I can test it locally

**Comment by BlackDahlia313** [comment]
![image](https://github.com/scottyzen/woonuxt/assets/44903742/a2c9803c-b60a-4d4b-82d5-a8a10d0b7a45)
![image](https://github.com/scottyzen/woonuxt/assets/44903742/1c457794-aa51-4830-ab35-857b2a349d03)
 New testing endpoint is: https://rv.ruffino.pizza/graphql
 
 @scottyzen ty for taking a look.

**Comment by BlackDahlia313** [comment]
The freshly deployed ruffino.pizza one is the error I am seeing above with 2 simple products added.

With the wptest.motorcity.host graphl 

This is the error I am seeing:
https://github.com/scottyzen/woonuxt/issues/75

**Comment by BlackDahlia313** [comment]
@scottyzen 

https://rv.ruffino.pizza/graphql works now with WooGraphQL v0.17.0 and deploys normally. 

wptest.motorcity.host/graphql - doesnt matter if its 17.0 or 18.2 it has the same error as this:

https://github.com/scottyzen/woonuxt/issues/75

![image](https://github.com/scottyzen/woonuxt/assets/44903742/8e7d51f3-3b14-4691-aae1-bf7178e52434)

**Comment by BlackDahlia313** [comment]
> @scottyzen
> 
> https://rv.ruffino.pizza/graphql works now with WooGraphQL v0.17.0 and deploys normally.
> 
> https://wptest.motorcity.host/graphql - doesnt matter if its 17.0 or 18.2 it has the same error as this:
> 
> #75
> 
> ![image](https://user-images.githubusercontent.com/44903742/278125935-8e7d51f3-3b14-4691-aae1-bf7178e52434.png)

This one was resolved by moving the woographql to 0.15. The rest is updated though I am confused. It doesnt work on 17 like the new deploy does.

Both frontend codebases are updated to the latest release. So both deploy now. One on woograph 17 and the other 15. But both I cant work with locally because of the @intlify/vue-i18n-bridge thing.

**Comment by ry-jp** [comment]
Can confirm, having the same exact issue here. I too only had luck deploying when WooGraphQL was on 1.15.0.
Has been occuring for a couple a weeks now. It's like WooNuxt is not compatible with the current version of WooGraphQL

**Comment by BlackDahlia313** [comment]
I was able to resolve the working locally part by moving the project to my C drive from my D drive. I can now NPM or PNPM install and run the project locally. 

But whats strange is about the woograph above now.

**Comment by kidunot89** [comment]
@scottyzen There were some minor breaking changes in between WooGraphQL v0.17.x -> v0.18.x

`allowedCountryStates` was renamed to `countryStates`.
`RootQueryToProductConnection*` types were replaced with `RootQueryToProductUnionConnection` to add better support for mixed results. To better explain these changes here is an example query

```graphql

query {
  countryStates(country: US) {
    code
    name
  }
  products(first: 10) {
    edges {
      cursor
      node {
        id
        name
        averageRating
        type
        ... on Product {
        	date
          terms {
            nodes {
              id
              name
            }
          }
        }
        ... on ProductWithPricing {
          price
          salePrice
          regularPrice
        }
        ... on ProductWithVariations {
          variations {
            nodes {
              id
              databaseId
              name
              price
              salePrice
              regularPrice
              attributes {
                nodes {
                  id
                  name
                  value
                }
              }
            }
          }
        }
      }
    }
  }
}

```

**Comment by scottyzen** [comment]
Hi All,

This should be okay now. WooNuxt was missing a few bits but is fully
compatible and should be used with the latest version of WooGraphQL
<https://github.com/wp-graphql/wp-graphql-woocommerce/releases/tag/v0.18.2>
 now.
I've updated the list of versions to work with:
https://github.com/scottyzen/woonuxt#tested-up-to

Kind regards
Scott

**Comment by ry-jp** [comment]
Glad to see yoou fixed it. I messaged him on slack informing him of the compatibility and sent him the link to that thread. He caught it right away.

unfortunately doesn't look like it's completely fixed. I updated to Woographql 0.18.2 and i'm still getting the same error:
[image.png]

When I go back to 0.15.0 and change countryStates to allowedCountryState, it deploys properly and I no longer get that error. Please double check that it should be working because I am not having luck still.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by ry-jp** [comment]
Here is the error i'm getting as of right now.
![image](https://github.com/scottyzen/woonuxt/assets/104651590/52139433-f086-48d7-9de6-79606fd7cbe2)

**Comment by kidunot89** [comment]
@ry-jp can you take a screenshot of the error your receiving

**Comment by ry-jp** [comment]
let me try it locally with a fresh clone of the original repo.

**Comment by kidunot89** [comment]
@ry-jp Thought so, this is due to a new Enumerator I added. It's kind of a bug. The workaround is you need to add a product attribute in the WordPress dashboard on the back end, by going to Product > Attributes. It doesn't matter what the name is or anything one product attribute just needs to exist

**Comment by ry-jp** [comment]
Ahh, alright. Let me try that real fast

**Comment by ry-jp** [comment]
Well this is interesting. It worked and deployed. 
![image](https://github.com/scottyzen/woonuxt/assets/104651590/f12ddb83-f819-4be9-a6d2-232bc8ef64c4)

Now i'm getting a "page not found" on Netlify. 
![image](https://github.com/scottyzen/woonuxt/assets/104651590/7e29f55a-4737-4d55-b69c-55cbe0cb37bc)

**Comment by ry-jp** [comment]
This is with a fresh fork on the woonuxt repo by the way.

**Comment by ry-jp** [comment]
Locally it works fine... and when I run a npm run generate it builds fine as well, and I can still view from local host. 

Another potential bug @scottyzen :
it's also not showing any products on /product page, but it shows products when I find them via category
![image](https://github.com/scottyzen/woonuxt/assets/104651590/dab223c2-6a64-4eeb-b15e-c61d62bd4702)

![image](https://github.com/scottyzen/woonuxt/assets/104651590/7346a742-9612-4d20-8426-eac3cb7cd4cc)

![image](https://github.com/scottyzen/woonuxt/assets/104651590/6d8f92ca-60ba-41b4-9bfd-32869d60a7bd)

**Comment by ry-jp** [comment]
Got it to deploy but only from a new instance FROM, woonuxt-settings. I can not get it to build from a forked repository.

**Comment by BlackDahlia313** [comment]
> @ry-jp Thought so, this is due to a new Enumeration I added. It's kind of a bug. The workaround is you need to add a product attribute in the WordPress dashboard on the back end, by going to Product > Attributes. It doesn't matter what the name is or anything one product attribute just needs to exist

This is good to know. My freshly deployed test had products on v18+ with no attributes and saw that enum issue. I'll test that. 

But the older deploy that had attributes already had the same issue as issue #75. I'll check the latest commit and see if that helps for the older version. 

Thanks for the info guys!

**Comment by ry-jp** [comment]
> This is with a fresh fork from the woonuxt repo by the way. I have not added anything to it other than my environment variables

Figured out why it won't deploy when you fork this repo. The publish directory on netlify needs to be "dist" instead of "nuxt/dist"

**Comment by BlackDahlia313** [comment]
thank you. My issue is now resolved with both projects.
