### ISSUE TITLE
Revision control request

### ISSUE THREAD

**Issue by zackha** [scottyzen/woonuxt#8]
Hi @scottyzen 

I felt the need to revise Woonuxt for use in the textile industry like Zalando. First, I started by revising the product page. Could you please examine the compatibility with the source code? I'll fix the places you want me to fix, if you like it, i can pull request it to the source code.

````
My fork link = https://github.com/zackha/woonuxt.git

WORDPRESS_URL = https://rays.terodon.com
GRAPHQL_ENDPOINT = https://rays.terodon.com/id8zCEmPUIOZc8eam74
DOMAIN = rays.terodon.com
STRIPE_PUBLISHABLE_KEY = pk_test_hYushiff8SDLQBTdWpHx5s192OzMpEh6o
GOOGLE_TAG_MANAGER_ID = G-80Z4HSDMGR
````

Best Regards,

**Comment by scottyzen** [comment]
Hi @zackha,

I just had a look at your site there. Some of the changes look really nice and suit your store better. Although the image sizes are not as well laid out on the few stores that I tried. The beauty of this kind of starters is it's easy to apply the best kind of style for the required style of storefront. Personally, I wouldn't be mad about how [Zalando](https://www.zalando.ie/) looks. 

I really like the way you have {{selectedValue}} shown beside the active variation. It looks really nice and is definitely a UX improvement. I refactored it slightly so it shows the correct value when there are multiple attributes on a single product.

Thanks again Zack, It's nice seeing how different store data looks 👍🏻

**Comment by zackha** [comment]
Thanks for your nice feedback, if you think my fork is ok for your source code, I can request a pull and proceed as a fork of the project. or as a second alternative to your source code I could go ahead as a second demo repository. I think it will be an excellent alternative for textile companies using Woocommerce.

**Comment by scottyzen** [comment]
You're welcome. I think it would be a good idea to put a link to your demo into the readme file. And the link to your fork. If you set it up on Netlify and send me the URL I'll add it. 😁

**Comment by zackha** [comment]
Hi @scottyzen

I deployed the second demo to netlify 🚀 [woonuxt-zackha.netlify.app](https://woonuxt-zackha.netlify.app/)

Best Regards,
