### ISSUE TITLE
Issue with stripe 3DSecure

### ISSUE THREAD

**Issue by Vibesfr** [scottyzen/woonuxt#80]
Hi,

First congratulation for this amazing project.

I'm encountering an issue when using [3D Secure authentication](https://stripe.com/docs/testing?locale=en-EN#regulatory-cards) test card provided from stripe website (4000002760003184).

it doesn't show the 2FA popup but the order is created and set as Pending payment.

Is there a workaround to make this work.

Sincerely,
Léo

**Comment by scottyzen** [comment]
Thanks @Vibesfr . I'll have to take this away and do some testing. I'll get back to you with an update as soon as I can

**Comment by plcdnl** [comment]
Hi, same error here. Are there any news?

**Comment by scottyzen** [comment]
I've been looking into this. I might need to use a different NPM package than ```vue-stripe-js```. It looks like it hasn't been updated in awhile. If anyone has any suggestions a Stripe extensions for Nuxt I'd love to hear about it. I might need to just do a redirect to the Stripe checkout page. But I'd like to be able to use the card elements like the way it is now. ```@vue-stripe/vue-stripe``` might be another thing that could be used, but it seems to be lacking documentations.

I will keep ye posted as soon as I know more.

**Comment by GuillaumeDgr** [comment]
Hi, any update on this pls? 
Many thanks

**Comment by xairoo** [comment]
I am also looking for a fix to finally start my woonuxt store. These days so many people have to use 3-D Secure (and I am happy to have a additional security step).

**Comment by GuillaumeDgr** [comment]
Hi @scottyzen, sorry to bother you, any update or date with this functionnality pls? It’s annoying because it’s a very important feature these days :/

**Comment by scottyzen** [comment]
Hi @GuillaumeDgr, I didn't get much time lately. I've started on a local branch this week though. Haven't figured it out yet. But I'll push a PR as soon as I can.

**Comment by scottyzen** [comment]
Hi guys. I just about have 3DSecure sorted. Here's a link to the deploy branch with it enabled https://staging--sleepy-chandrasekhar-717c3d.netlify.app if you could take a look. I hope to have it merged into `Master` in the next couple of days.

**Comment by GuillaumeDgr** [comment]
Thanks a lot for your work !!
