### ISSUE TITLE
Product not showing

### ISSUE THREAD

**Issue by jujutsucode** [scottyzen/woonuxt#92]
I have a product and it doesnt show up on woonuxt netlify
![Screenshot_20231210-104525_Chrome](https://github.com/scottyzen/woonuxt/assets/138183266/82796d9d-4fcc-4e2d-912a-ecc9f6558363)
![Screenshot_20231210-104619_Chrome](https://github.com/scottyzen/woonuxt/assets/138183266/f699b73b-3386-4ea9-93fa-3db21c1aeafd)

**Comment by scottyzen** [comment]
Hi @jujutsucode. Can you email me your GraphQL endpoint and I'll take a look for you

**Comment by jujutsucode** [comment]
Ok, it succesfully showing product now after rebuilding.

**Comment by M-GRV** [comment]
Awesome! Just remember to do that after adding a new product and you will be good to go! :)
